"""create tables

Revision ID: 17146d39204c
Revises: 6bbc545b0d61
Create Date: 2023-06-19 15:49:03.494886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17146d39204c'
down_revision = '6bbc545b0d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
